### PR TITLE
✨ Role Segregation

### LINKED ISSUE #11: Segregate student and teacher roles
I swear I'm not racist

### PR DESCRIPTION
**Pull request by EvanZhouDev**
# Pull Request Check List

**Applicable issues**

- Closes #11

**Description of PR**

Separate Attendee and Host roles.

### CODE REVIEW

**Review by ThatXliner — APPROVED** [review]
UI LGTM! We just need to hook up functionality. Please resolve the merge conflicts. Once you're done with that, I can start hooking up the backend.

**Review by ThatXliner — APPROVED** [review]
Just looking at the code changes, LGTM. I'm going to hook up the UI before we merge

**Comment by ThatXliner** [comment]
Tests should fail btw (because snapshots)

**Comment by ThatXliner** [comment]
TODO: 
 - new db column in profiles
 - RLS policies to ensure only hosts can make groups/sessions and only attendees can join/attend

**Comment by ThatXliner** [comment]
All functional now! Just need tests

**Comment by EvanZhouDev** [comment]
Fixes still needed:
- [ ] Prevent hosts from accessing attendee view and vice versa
- [ ] Add log-out button on attendee side
- [ ] Bring back the warning about hosts not being able to Attend

**Comment by ThatXliner** [comment]
> Add log-out button on attendee side (There, but doesn't work)

Log out works, what do you mean?

**Review by ThatXliner — CHANGES_REQUESTED** [review]
Everything works but there is an issue where the data that should be managed by realtime (i.e. attendee/group list for host, group list for attendee) isn't being updated. Can you please help debug this issue? Is it an issue with react?

Preferably we should add tests for this PR

edit: [metadata](https://github.com/EvanZhouDev/zyma/pull/50/#issuecomment-1872620736) is also affected by this issue

**Comment by ThatXliner** [comment]
Tests are failing because of snapshot updates. I'll update them sooner or later

**Review by ThatXliner — APPROVED** [review]
I'll do a major check soon

**Comment by ThatXliner** [comment]
So I tested a little bit and theoretically we can ship now but I just want some more thorough tests before we continue

**Comment by ThatXliner** [comment]
Ready for merge after we update Linux snapshots

**Pull request merged**
